### ISSUE TITLE
ASLParser error with 64bit offset

### ISSUE THREAD

**Issue by lyuha** [LiveSplit/LiveSplit.ScriptableAutoSplit#52]
64bit game needs 64bit offset.

In example, Monster hunter world use 64bit offset for base address like `0x140000000`

Follow https://github.com/Haato3o/HunterPie/blob/master/HunterPie/address/MonsterHunterWorld.416251.map
```
Address BASE 0x140000000
// Others
```

ASL occurs `System.InvalidCastException: Specified cast is not valid` at https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/blob/b25662cdad0d7b81eb186183e3557929fffc497b/ASL/ASLParser.cs#L54-L55

To use ASL for MHW, need to support 64 bit offset.

Relative Issue : https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/issues/47

**Comment by Voxelse** [comment]
If I'm not wrong, the module size is bound to an int so what you are using here is an absolute address where it should be a relative address.

If you want to do it from the state block you'll need to find the module name and your relative address which should something like this "MonsterHunterWorld.exe+0x12345678" or a different name if the address is not located in the main module.

Or, if you want to use the absolute address, you will need to manually create a DeepPointer with the right constructor instead of automatically creating it from the state block.

**Comment by lyuha** [comment]
Thanks for reply.

I solved with second option like `MonsterHunterWorld.exe+0x12345678`.


Additionally, how to manually create a deeppointer? How can access `ComponentUtil` at ASL? Could you give some reference?

**Comment by Voxelse** [comment]
The Component Util classes are straight accessible from the ASL.

You can create your absolute DeepPointer like `new DeepPointer((IntPtr)0x140000000, 0x0, ...);`
from the constructor `DeepPointer(IntPtr absoluteBase, params OffsetT[] offsets)`

Then you can use the functions to Deref the addresses but I advise you to put the DeepPointer in a MemoryWatcher, itself in a MemoryWatcherList if you have many of them, so you can have the **.Current** and **.Old** behaviors.
There are many different implementations available in here [ASL scripts](https://fatalis.pw/livesplit/asl-list/) (where you can filter by behavior -> Memory Watcher)

Though, if making the pointers from the state block is all you need, I wouldn't recommend switching to DeepPointers unless you want better control or do more complex stuff with your pointers.
